version: '3'

services:
  app:
    container_name: app
    build: .
    command: gunicorn cadastro.wsgi:application --reload --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    env_file:
        - ./.env  
    depends_on:
      - db
    networks:
      - backend_net
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
        - ./.postgres_data:/var/lib/postgresql/data/  
    env_file:
        - ./.env.db
    shm_size: 1g
    networks:
      - backend_net
volumes:
  postgres_data:

  static_volume:
  media_volume:
  backups:

networks:
  backend_net:
